# Generated by Django 4.0.5 on 2022-06-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_label_labeltaskintermediate_labels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltaskintermediate',
            old_name='labels',
            new_name='label',
        ),
    ]
